export const ADD_CART_SUCESS = "ADD_CART_SUCESS";
export const REMOVE_CART_SUCESS = "REMOVE_CART_SUCESS";
export const UPDATE_AMOUNT_SUCESS = 'UPDATE_AMOUNT_SUCESS';
export const DELET_CART_SUCESS = 'DELET_CART_SUCESS';
export const CHECKOUT_SUCESS = 'CHECKOUT_SUCESS';
